# Generated by Django 3.1.7 on 2021-04-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='country',
            field=models.CharField(default='Anniyan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(default='Testing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='state',
            field=models.CharField(default='Indian', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='username',
            field=models.CharField(default='kabali', max_length=100),
            preserve_default=False,
        ),
    ]
