# Generated by Django 3.1.7 on 2021-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20210409_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='cont',
            field=models.CharField(default='migrations', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receive',
            name='desc',
            field=models.CharField(default='migrations', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receive',
            name='img',
            field=models.ImageField(default='migrations', upload_to='pics'),
            preserve_default=False,
        ),
    ]
