# Generated by Django 3.1.7 on 2021-04-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210413_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='donor_name',
            field=models.CharField(default='Anniyan', max_length=100),
            preserve_default=False,
        ),
    ]
