# Generated by Django 3.1.7 on 2021-04-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_receive_donor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.CharField(max_length=100)),
                ('cont', models.CharField(max_length=100)),
                ('donor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='receive',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
