# Generated by Django 3.1.7 on 2021-05-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20210430_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2016-05-18T15:37:36.993048Z'),
            preserve_default=False,
        ),
    ]
